[tool.poetry]
name = "faq"
version = "0.1.0"
description = "Auto FAQ builder"
authors = ["Will McGugan <willmcgugan@gmail.com>"]
license = "MIT"
readme = "README.md"

include = [
    "src/textual/py.typed"   
]

[tool.poetry.scripts]
faq = "faq.cli:run"

[tool.black]
includes = "src"

[tool.poetry.dependencies]
python = "^3.8"
rich = "^12.6.0"
jinja2 = "^3.1.2"
click = "^8.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
